Add test cases for Resources Page
WomenWhoCode/london pull request #192
Opened 2023-11-05 10:21 UTC by nora-weisser

## Description

Add test cases for Resources Page:
1. Copied .yml files to the test data folder as a reference (expected result)
2. Checked UI Elements
3. Ensure that every element on the card contains expected information
4. Checked links, if it is not broken and the value as expected

## Change Type
- [x] New Feature

## Related Issue
https://github.com/WomenWhoCode/london/issues/173

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] I checked and followed the [contributor guide](CONTRIBUTING.md) 
- [x] I have tested my changes locally.
- [x] I have added a screenshot from the website after I tested it locally

2023-11-05 11:12 UTC, dricazenck reviewed
Small details, only.

2023-11-05 11:12 UTC, dricazenck commented on e2e-tests/cypress/support/locators/resources_page/resources_page.locate.js
> +            .should('eq', 200)
Please add respective commas in the end

2023-11-05 11:12 UTC, dricazenck commented on e2e-tests/cypress/support/locators/resources_page/resources_page.locate.js
> +    .shouldBeVisible().should('contain', 'Events')
Also format seems to be wrong. Missing commas as well.

2023-11-05 13:16 UTC, nora-weisser commented on e2e-tests/cypress/support/locators/resources_page/resources_page.locate.js
> +            .should('eq', 200)
Very good point! 👍 
I've created `helper.js` to move this part of the code and also created `SUCCESS_STATUS_CODE` variable there.

2023-11-05 13:17 UTC, nora-weisser commented on e2e-tests/cypress/support/locators/resources_page/resources_page.locate.js
> +    .shouldBeVisible().should('contain', 'Events')
I believe that you meant semicolon at the end, right?

2023-11-05 14:18 UTC, dricazenck approved these changes
Just style, but once we are adding semicolon, she should keep the style.

2023-11-05 14:18 UTC, dricazenck commented on e2e-tests/cypress/support/locators/resources_page/resources_page.locate.js
> +const BLOG_POSTS_FILE = 'test_data/blogs.yml'
Semicolon missing.

2023-11-05 14:18 UTC, dricazenck commented on e2e-tests/cypress/support/locators/resources_page/resources_page.locate.js
> +  }
Semicolon missing

2023-11-05 14:18 UTC, dricazenck commented on e2e-tests/cypress/support/locators/resources_page/resources_page.locate.js
> +    .shouldBeVisible().should('contain', 'Events')
Yes sorry.

2023-11-05 14:18 UTC, dricazenck commented on e2e-tests/cypress/support/locators/resources_page/resources_page.locate.js
> +  }
; Missing

2023-11-05 14:18 UTC, dricazenck commented on e2e-tests/cypress/support/locators/resources_page/resources_page.locate.js
> +      .should('contain', 'Blog Posts')
; Missing

2023-11-05 14:18 UTC, dricazenck commented on e2e-tests/cypress/support/locators/resources_page/resources_page.locate.js
> +        })
```suggestion
        });
```

2023-11-05 14:35 UTC, vamelchenia commented on e2e-tests/cypress/e2e/resources_page.feature
I didn't divide verifying sections on the same page making them in one step and one function. This is not bad approach which you applied but we'd better have consistency across our code. So I suggest that you (1) wrap your steps and functions into one, or do the same in other tests

2023-11-05 14:37 UTC, vamelchenia commented on e2e-tests/cypress/support/helper.js
Instead of these helpers I recommend moving it to custom commands. We already have one called 'shouldBeVisible'

2023-11-05 14:38 UTC, vamelchenia requested changes
Left a couple of comments

2023-11-05 15:25 UTC, nora-weisser commented on e2e-tests/cypress/e2e/resources_page.feature
Good point about consistency. I divided into sections, because it might be simpler to troubleshoot and maintain in the future, also it is more easier to understand right from feature file what UI Elements Verification includes.

2023-11-05 15:33 UTC, nora-weisser commented on e2e-tests/cypress/support/helper.js
Good point! I moved function to `commands.js`!

2023-11-05 15:40 UTC, nora-weisser commented on e2e-tests/cypress/e2e/resources_page.feature
If you are agree with this point, I can refactor in the next PR, since it will be easier to review.

2023-11-05 18:13 UTC, vamelchenia commented on e2e-tests/cypress/e2e/resources_page.feature
Yes, please. Also I would define somehow in steps phrases that they belong to a particular page, for example:
    And I verify UI elements on Resources Section ->  And I verify UI elements on Resources Section of the Resources page

2023-11-05 18:26 UTC, vamelchenia commented on e2e-tests/cypress/support/locators/resources_page/resources_page.locate.js
> +  validateResourcesCards = () => {
Let's separate the logic of getting locators and validating their base parameters from data verification. I would propose to make getResourcesCards() function here and create validateResourcesData() in resources.page.js file. 
This locators section is a low level of interacting with HTML elements.

2023-11-05 18:27 UTC, vamelchenia requested changes
Added one more conceptual point

2023-11-06 18:53 UTC, nora-weisser commented on e2e-tests/cypress/support/locators/resources_page/resources_page.locate.js
> +  validateResourcesCards = () => {
I splitted those functions into get and validate actions

2023-11-06 19:12 UTC, vamelchenia commented on e2e-tests/cypress/support/locators/resources_page/resources_page.locate.js
> +  validateResourcesCards = () => {
Ok, let it be this way. I just though of moving data verification to a 'page' file. It's not critical

2023-11-06 19:13 UTC, vamelchenia approved these changes
Left a comment just FYI, nothing critical

2023-11-06 22:57 UTC, merged

2023-11-06 22:58 UTC, vamelchenia commented
https://github.com/WomenWhoCode/london/issues/173